spring:
  profiles: local
server:
  port: 9000
datasource:
  url: jdbc:h2:mem:realworld_spring_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
  username: sa
  password:
  driver-class-name: org.h2.Driver
  platform: h2