spring:
  profiles: local
server:
  port: 8888
datasource:
  url: jdbc:h2:mem:realworld_spring_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=TRUE
  username: sa
  password:
  driver-class-name: org.h2.Driver
  platform: h2
---

sql:
  getAllArticles: "select a.slug, a.title, a.description, a.body, a.created_at, a.updated_at, a.favorite_count, u.username, u.bio, u.image, (select count(*) from follows where follower_user_id = 1 and following_user_id = a.author_id) as following, (select count(*) from favorites where article_id = a.id and user_id = 1) as favorited from articles a join users u on a.author_id=u.id" #@TODO: this user id is hard coded
  getUserByUsername: "select u.email, u.username, u.password, u.image, u.bio from users u where u.username = ?;"
